---
apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: ran-cu-delhi-server-profile-cu-dell-r640-00-pao-profile-cu-dell-r640-00
spec:
  cpu:
    isolated: "1-19,21-39"
    reserved: "0,20"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 64
      node: 0 
    - size: "1G"
      count: 64
      node: 1 
  numa:
    topologyPolicy: best-effort  nodeSelector:
    node-role.kubernetes.io/ran-cu-delhi-server-profile-cu-dell-r640-00: ""