---
apiVersion: fpga.intel.com/v1
kind: N3000Cluster
metadata:
  name: n3000
  namespace: vran-acceleration-operators
spec:
  nodes:
    - nodeName: atria11
      fpga:
        - userImageURL: http://9.42.98.148/vRAN-4G-2x1x25Gx2FVL-0x0023F0050A010507_unsigned.bin
          PCIAddr: "0000:6a:00.0"
          checksum: "234a08fab909609f754d21756a2c4395"
    - nodeName: atria12
      fpga:
        - userImageURL: http://9.42.98.148/vRAN-4G-2x1x25Gx2FVL-0x0023F0050A010507_unsigned.bin
          PCIAddr: "0000:6a:00.0"
          checksum: "234a08fab909609f754d21756a2c4395"
    - nodeName: atria15
      fpga:
        - userImageURL: http://9.42.98.148/vRAN-4G-2x1x25Gx2FVL-0x0023F0050A010507_unsigned.bin
          PCIAddr: "0000:6a:00.0"
          checksum: "234a08fab909609f754d21756a2c4395"