---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./du-1  
  - ./du-2  

resources:
  - 40-cu-du-cluster-qa-new-mysore-supermicro-du.yaml  
  - 50-cu-du-cluster-qa-new-mysore-supermicro-du-00-pre.yaml
  - 60-cu-du-cluster-qa-new-mysore-supermicro-du-01-post.yaml  
  - 70-cu-du-cluster-qa-new-mysore-supermicro-du-02-configs.yaml
