---
apiVersion: fpga.intel.com/v1
kind: N3000Cluster
metadata:
  name: n3000
  namespace: vran-acceleration-operators
spec:
  nodes:
    - nodeName: supermicro-worker-1
      fpga:
        - userImageURL: http://172.29.231.89/sr_vista_rot_4x25G-v1.3.16.bin
          PCIAddr: "0000:b6:00.0"
          checksum: "6a2ec5f927a31aeeb1eac9863eb6e550"
    