---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
#    argocd.argoproj.io/sync-wave: "30"
  name: nodes-label-job-dev-worker-2
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/node
              echo ""
              echo -n "Add node labels"
              until oc wait --selector=node-role.kubernetes.io/ran-du-vizag-server-profile-cu-dell-r640-01='',kubernetes.io/hostname=dev-worker-2 --for=condition=ready nodes
              do
                echo -n "...still waiting for applying labels"
                oc label node dev-worker-2 node-role.kubernetes.io/ran-du-vizag-server-profile-cu-dell-r640-01=""
                oc label node dev-worker-2 ran.openshift.io/vizag-ptp-server-profile-cu-dell-r640-01=""
                oc label node dev-worker-2 ran.openshift.io/n3k=""
                oc label node dev-worker-2 ran.openshift.io/ptp=""
                oc label node dev-worker-2 ran.openshift.io/sriov=""

                sleep $SLEEP
              done
              echo "DONE"
          imagePullPolicy: Always
          name: nodes-label-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30