---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-vizag-vcu
  name: vm-vizag-cu-01
  namespace: altiostar-4g-cu-vizag
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-vizag-vcu
    spec:
      nodeSelector:
        node-role.kubernetes.io/ran-cu-vizag-server-profile-cu-dell00: ""
      domain:
        cpu:
          cores: 4
          dedicatedCpuPlacement: True
        devices: 
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
            -  name: nic0
               masquerade: {}
            -  name: nic1
               macAddress: 56:90:90:01:01:01
               sriov: {}
            -  name: nic2
               macAddress: 56:90:90:01:01:02
               sriov: {}
            -  name: nic3
               macAddress: 56:90:90:01:01:03
               sriov: {}
        resources:
          requests:
            memory: "16Gi"
        memory:
          hugepages:
            pageSize: "1Gi"
      volumes:
      - dataVolume:
          name: vizag-cu-01-dv
        name: datavolumedisk1
      - cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              eth0:
                dhcp4: true
                set-name: eth0
              ens1:
                addresses: [ 10.27.5.201/24 ]
                set-name: ens1
                match:
                  macaddress: 56:90:90:01:01:01
              ens2:
                addresses: [ 10.27.6.201/24 ]
                set-name: ens2
                match:
                  macaddress: 56:90:90:01:01:02
              ens3:
                addresses: [ 10.27.3.201/24 ]
                set-name: ens3
                match:
                  macaddress: 56:90:90:01:01:03
          userData: |-
              #cloud-config
              hostname: rhocp-vizag-cu-01
              fqdn: rhocp-vcu1.rma.lan
              write_files:
              -   path: /mnt/prov.ini
                  content: |
                    default-route: eth0
                    ntp-ip: 10.27.5.10
                    ns-ip: 10.27.5.10
                    ems-fqdn: 10.27.5.101
                    ems-snmp-port: 162
                    oran-support: yes
                    enb-id: 17001
                    nw-type: nw_type
                    nw-init-method: method
                    mgmt-nics: 56:90:90:01:01:01
                    mh-nics: 56:90:90:01:01:02
                    bh-nics: 56:90:90:01:01:03
                  owner: root:root
                  permissions: '0644'
        name: cloudinitdisk
      networks:
        - name: nic0
          pod: {}
  
        - multus:
            networkName: vizag-vran-mgmt
          name: nic1
  
        - multus:
            networkName: vizag-vran-mh-a
          name: nic2
  
        - multus:
            networkName: vizag-vran-bh-s1c-a
          name: nic3
  dataVolumeTemplates:
  - metadata:
      name: vizag-cu-01-dv
    spec:
      pvc:
        storageClassName: hostpath-provisioner
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      source:
        http:
          url: >-
            http://fedora.c3sl.ufpr.br/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.qcow2
#        registry:
#          url:  "docker://castor-registry.castor.altiostar.lan:5000/vcu-4g-60"
#          certConfigMap: registry-pod2-certs-vizag-cu
#          secretRef: registry-pod2-certs-vizag-cu