---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-vizag-server-profile-cu-dell-r640-01

commonAnnotations:  
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/compare-options: IgnoreExtraneous

resources:
  - 00-hook-mcp-wait-job-vizag.yaml
  - 01-config-scratchspace.yaml
