---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./mysore/supermicro/cu

# Apps of Apps
resources:

  # - 10-gemini.yaml
  - 10-cu-du-cluster-qa-new.yaml
  - 20-cu-du-cluster-qa-new-sriovconfig.yaml
  - 30-cu-du-cluster-qa-new-ptpconfig.yaml