---
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  additionalTrustedCA:
    name: quay-mgmtcluster-config
  registrySources:
    insecureRegistries:

mirrorregistry.rtp.raleigh.ibm.com:5000
    
    - mirrorregistry.rtp.raleigh.ibm.com:5000
