 
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vizag-sriov-vfio-dell00-server-profile-cu-dell00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/vizag-sriov-vfio-server-profile-cu-dell00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 32
  nicSelector:
    vendor: "15b3"
    deviceID: "1015"
    pfNames:
          - ens2f0#24-31
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vizag-sriov-a-vfio-dell00-server-profile-cu-dell00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio_a"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/vizag-sriov-vfio_a-server-profile-cu-dell00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 32
  nicSelector:
    vendor: "15b3"
    deviceID: "1015"
    pfNames:
          - ens2f0#0-5
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: vizag-sriov-vfio-b-dell00-server-profile-cu-dell00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio_b"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/vizag-sriov-vfio_b-server-profile-cu-dell00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 32
  nicSelector:
    vendor: "15b3"
    deviceID: "1015"
    pfNames:
          - ens2f0#16-18
    
