---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-vizag-server-profile-cu-dell00

resources:
  # SRIOV Configs
  - 00-hook-mcp-wait-job-vizag.yaml
  - 00-vizag-sriov-namespace.yaml
  - 00-vizag-sriov-node-policy.yaml
  - 01-vizag-sriov-networks.yaml
