---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    # argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: snp-wait-cu-delhi-server-profile-cu-dell-r640-00
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: vran-quay-registry-quay-openshift-operators.apps.mgmtcluster.rtp.raleigh.ibm.com/ocp4/openshift4:4.6.16-cli
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/mcp
              echo ""
              echo -n "Waiting for the sriovnodepolicy to be created."
              SNP_AVAILABLE=0
              sleep $SLEEP
              until [ $SNP_AVAILABLE -ge 1 ]
              do
                SNP_AVAILABLE=`oc get SriovNetworkNodePolicy  -n openshift-sriov-network-operator | grep -o "$SNP_NAME" | wc -l`
                echo -n "Waiting for the sriovnodepolicy to be created."
                sleep $SLEEP
              done
              echo "DONE"
          imagePullPolicy: Always
          name: sriovnodepolicy-wait-job
          env:
          - name: SLEEP
            value: "5"
          - name: SNP_NAME
            value: "delhi-.*-server-profile-cu-dell-r640-00"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30