---
apiVersion: v1
data:  
  mirrorregistry.rtp.raleigh.ibm.com..5000: |
    -----BEGIN CERTIFICATE-----
    MIIDpzCCAo+gAwIBAgIURpgdKSUVtXYHhhzNW5HIU/DWTDMwDQYJKoZIhvcNAQEL
    BQAwYzELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAktBMQswCQYDVQQHDAJTWjENMAsG
    A1UECgwESUJNLjErMCkGA1UEAwwibWlycm9ycmVnaXN0cnkucnRwLnJhbGVpZ2gu
    aWJtLmNvbTAeFw0yMTA1MjQwODIwNTdaFw0zMTA1MjIwODIwNTdaMGMxCzAJBgNV
    BAYTAklOMQswCQYDVQQIDAJLQTELMAkGA1UEBwwCU1oxDTALBgNVBAoMBElCTS4x
    KzApBgNVBAMMIm1pcnJvcnJlZ2lzdHJ5LnJ0cC5yYWxlaWdoLmlibS5jb20wggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD5Pmb0YdeOstCAcJNC5Z3FE9Nc
    qQTqplPb/XPuwGP60bl5YpPDzmRud3wow32H/HePDoj/kKu/wZIkEP5Dp5W1wnWm
    /6TWZJkEpdMZ89tfiL7n67FVJKz+DmgyjqqJhQhn23Shr7vep6gGQAXcLPZJKcc3
    85VUJkzzS1ikU3WhqsxuhUO26XRR4nNRWUXWbRlzd51hQN9/mQ5xUcl7sRRGzRAL
    YyuUQejypojxY31HOz1MUJX0KthivXKl7eq4HXUUA3LzN1JfJQ2ni8F0aZlFZjip
    3VJC6OHGkRV/oMZwmaW2R9S8Yleb4a7Y7rNV6dsv+rjJytFwaRY18YvsuxihAgMB
    AAGjUzBRMB0GA1UdDgQWBBTWi9/eyJsHEaDAKO78zBAmg/1oNDAfBgNVHSMEGDAW
    gBTWi9/eyJsHEaDAKO78zBAmg/1oNDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3
    DQEBCwUAA4IBAQDvlhCVQBbiaf7Q4fh9Jujsgh2B9ik6QJn4P0WOhf6L42h52S/a
    5ldXZAy92zhvbmpDifQEm0dqK3s6Q/3VkKL7xWSGpIC7hN/k/bgKNE+hLJBGD6KT
    ILmWe/9Z79rRpRzWurRSYFjZrLqN0aEM8i/HVfI0E3wBV9uNQMTObp5F0XHxoDjF
    0njH+fytlBw3NkObGd3oGAdPrUwCo0FPxuXapYspQctOXFe+ayusCHyl1ZfQIXjJ
    vKnWZkAr7QKr5nN7dasSBIQfcOQeCbuS797FuRCbu4tcDnUgdBUv4Ee3S57BOYE4
    d68O2+9bhNxyYMffwWAyLps43wHkEIRl1vjx
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: quay-mgmtcluster-config
  namespace: openshift-config