---
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  additionalTrustedCA:
    name: quay-mgmtcluster-config
  registrySources:
    insecureRegistries:
    - mgmtcluster-registry-quay-quay-enterprise.apps.mgmtcluster.altiostar.lan:443
    - mgmtcluster-registry-quay-quay-enterprise.apps.mgmtcluster.altiostar.lan      