---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-du-vizag-server-profile-cu-dell-r640-01

commonAnnotations:  
#  argocd.argoproj.io/sync-wave: "10"
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/compare-options: IgnoreExtraneous  


resources:
  - 00-hook-dev-worker-2-wait-job-vizag.yaml

  - 00-mcp-ran-du-vizag-server-profile-cu-dell-r640-01.yaml
  - 01-pao-ran-du-vizag-server-profile-cu-dell-r640-01-pao-profile-cu-dell-r640-00.yaml
#  - 00-node-labels.yaml
#  - 01-mcp-wait-job-sa-role.yaml