 
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: bangalore-sriov-vfio-smci00-server-profile-du-supermicro00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/bangalore-sriov-vfio-server-profile-du-supermicro00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 32
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens2f1#0-5
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: bangalore-sriov-vfio-ar-smci00-server-profile-du-supermicro00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio_ar"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/bangalore-sriov-vfio_ar-server-profile-du-supermicro00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 32
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens2f1#16-18
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: bangalore-sriov-netdevice-smci00-server-profile-du-supermicro00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_netdevice"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/bangalore-sriov-netdevice-server-profile-du-supermicro00: ""
  deviceType: netdevice
  priority: 10
  #mtu: 1500
  numVfs: 32
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens2f1#20-25
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: bangalore-sriov-netdevice-fh-smci00-server-profile-du-supermicro00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_netdevice_fh"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/bangalore-sriov-netdevice_fh-server-profile-du-supermicro00: ""
  deviceType: netdevice
  priority: 10
  #mtu: 1500
  numVfs: 32
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
          - ens2f1#28-31
    
