---
apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: ran-du-bangalore-server-profile-du-supermicro00-pao-profile-du-supermicro00
spec:
  cpu:
    isolated: "1-19,21-39"
    reserved: "0,20"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 64
      node: 0 
  numa:
    topologyPolicy: best-effort    
  realTimeKernel:
    enabled: true 
  nodeSelector:
    node-role.kubernetes.io/ran-du-bangalore-server-profile-du-supermicro00: ""