---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - 40-controlplane-cluster-1-mysore-supermicro-du.yaml  
  - 50-controlplane-cluster-1-mysore-supermicro-du-00-pre.yaml
  - 60-controlplane-cluster-1-mysore-supermicro-du-01-post.yaml  
  - 70-controlplane-cluster-1-mysore-supermicro-du-02-configs.yaml
