---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-pod2-certs-bangalore-cu
  namespace: altiostar-4g-cu01-bangalore
data:
    domain.crt: |
    -----BEGIN CERTIFICATE-----
MIIDjzCCAnegAwIBAgIBATANBgkqhkiG9w0BAQsFADBpMWcwZQYDVQQDDF52cmFu
LXF1YXktcmVnaXN0cnktcXVheS1vcGVuc2hpZnQtb3BlcmF0b3JzLmFwcHMubWdt
dGNsdXN0ZXIucnRwLnJhbGVpZ2guaWJtLmNvbS1jYUAxNjIzMzM2MzQxMB4XDTIx
MDYxMDEzNDU0MFoXDTIyMDYxMDEzNDU0MFowaTFnMGUGA1UEAwxednJhbi1xdWF5
LXJlZ2lzdHJ5LXF1YXktb3BlbnNoaWZ0LW9wZXJhdG9ycy5hcHBzLm1nbXRjbHVz
dGVyLnJ0cC5yYWxlaWdoLmlibS5jb20tY2FAMTYyMzMzNjM0MTCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBANPhgIFa1W23+OBFqJbHF+ZQuKlPo34rD6PL
ks/6xH5ZwJSFcuRXpZBfTuh16naxmcBE4iJAT6vVj26uK3kjY3RW53hFvg6JmHIZ
bj18AVplOfSAI0Auxqg0ouUgAkMQg+IYhGP967TbHCUBk4E5bBOSSfQX/Z87SBkV
6zeIMnSjyASVEvFPJ/O5XE6GIdE/5mLAqDXfqkab9EN9Nd3KZEsCqELh4BVREDjB
YrRbCgc2/Ecjt0C9urq2TCYUSXlxkRfLujczeL8kVwkMJV2NQ+wEUOGmIfn4/Ck1
23I93MhxjFT2Su/2nLSOLObe1yU7Yjp2oMQV5VE2T2ssgoZdVSMCAwEAAaNCMEAw
DgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMMVoXI7
ar0G2FK9JN1Rm5E8sMIkMA0GCSqGSIb3DQEBCwUAA4IBAQA/K0VtmJRve1i78oGd
mKdg8BSvFEmxkXQGzlInDePbpPehhDTjNDS4eY4nHG/eVwEstLx049A1A8aY91zy
y8k82uTIqmhkedmhY4fIE/ULFBp//QLZIAw1K6NpCSdaJ5SWtmeS91mvpR/Ogf0n
vruFceLZCNnfTDtkTIr78VQeofJ2nNpVpIIQf6vEjt49nJaeRdl1td6U/g+euqKN
DUdJxVrmDynByaJ6bdohIWA5MQ5o6GdYZ8Nnbj2lNaJGpSjSmxJkjE2NVeEjPwF6
z75nNd3O9cqZtim6OUefeGM1EkBT/i/6pmEsVc21bC7XLndZ1XlGLdEt0p2vJZCJ
uOiR
-----END CERTIFICATE----- 
  