---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-bangalore-server-profile-cu-dell00

commonAnnotations:
 #argocd.argoproj.io/sync-wave: "20"
 argocd.argoproj.io/sync-options: Prune=false
 argocd.argoproj.io/compare-options: IgnoreExtraneous

# Apps of Apps
resources:
  - 90-vcu-cluster-bangalore-dell-cu01.yaml