---
apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: ran-cu-mysore-server-profile-cu-supermicro00-pao-profile-cu-supermicro00
spec:
  cpu:
    isolated: "1-19,21-39"
    reserved: "0,20"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 64
      node: 0
    - size: "1G"
      count: 64
      node: 1
  numa:
    topologyPolicy: best-effort
  nodeSelector:
    node-role.kubernetes.io/ran-cu-mysore-server-profile-cu-supermicro00: ""