---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-du-mysore-server-profile-du-dell-r640-00

commonAnnotations:  
#  argocd.argoproj.io/sync-wave: "10"
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/compare-options: IgnoreExtraneous  


resources:
  - 00-mgmtacm-master-1-labels-job.yaml

  - 00-wait-job-sa-role.yaml
  - 01-mcp-wait-job-sa-rolebinding.yaml