---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-du-delhi-server-profile-du-dell00

commonAnnotations:
 #argocd.argoproj.io/sync-wave: "20"
 argocd.argoproj.io/sync-options: Prune=false
 argocd.argoproj.io/compare-options: IgnoreExtraneous
# Apps of Apps
resources:
  - 40-vcu-cluster-delhi-dell-du.yaml
  - 50-vcu-cluster-delhi-dell-du-00-pre.yaml
  - 60-vcu-cluster-delhi-dell-du-01-post.yaml
  - 70-vcu-cluster-delhi-dell-du-02-configs.yaml
